language: ruby
language: rake
language: node_js
rvm:
 - 2.2
 - jruby
#...
before_install:
  - sudo apt-get install fontforge eot-utils
  - wget http://people.mozilla.com/~jkew/woff/woff-code-latest.zip
  - npm install -g grunt-cli
  - npm install
script:
  - grunt test