language: ruby
language: rake
language: node_js
rvm:
 - 2.2
 - jruby
#...
before_install:
  - sudo apt-get install fontforge eot-utils
  - wget http://people.mozilla.com/~jkew/woff/woff-code-latest.zip
  - unzip woff-code-latest.zip -d sfnt2woff && cd sfnt2woff && make && sudo mv sfnt2woff /usr/local/bin/
  - npm install -g grunt-cli
  - npm install
script:
  - grunt test